---
title: "Pancreas Top Genes"
output:
  workflowr::wflow_html:
    code_folding: hide
date: "2025-05-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Pancreas c = 1 fit

```{r}
library(Matrix)
load("~/Documents/passPCA/inst/paper_figures/data/experiment_results.Rdata")
load("~/Documents/passPCA/inst/paper_figures/data/raw_data/pancreas.RData")
```

```{r}
i           <- which(sample_info$tech == "celseq2")
sample_info <- sample_info[i,]
counts      <- counts[i,]
sample_info <- transform(sample_info,celltype = factor(celltype))
```

```{r, results='hide'}
library(passPCA)

celltype <- sample_info$celltype
celltype <-
  factor(celltype,
         c("acinar","ductal","activated_stellate","quiescent_stellate",
           "endothelial","macrophage","mast","schwann","alpha","beta",
           "delta","gamma","epsilon"))

levels(celltype)[levels(celltype) == "activated_stellate"] <- "activated PSC"
levels(celltype)[levels(celltype) == "quiescent_stellate"] <- "quiescent PSC"

K <- 9
fit <- res_list$pancreas$`1`
colnames(fit$LL) <- paste0(
  "k", c(1, 3, 6, 5, 2, 7, 8, 9, 4)
)
colnames(fit$FF) <- paste0(
  "k", c(1, 3, 6, 5, 2, 7, 8, 9, 4)
)
fit$LL <- fit$LL[,paste0("k", 1:K)]
fit$FF <- fit$FF[,paste0("k", 1:K)]
topic_order <- rev(paste0(
  "k",
  c(1, 2, 4, 9, 5, 7, 3, 8, 6)
))
sp <- normalized_structure_plot(
  fit,
  grouping = celltype,gap = 30,perplexity = 70,n = Inf, font.size = 12,
  topics = topic_order
) 
```

```{r}
sp$plot
```


```{r, results='hide'}
library(clusterProfiler)
library(fgsea)
library(AnnotationDbi)
library(org.Hs.eg.db)

get_go_terms <- function(V) {
  
  K <- ncol(V)
  
  genes_vec <- c()
  go_terms_vec <- c()
  
  for (k in 1:K) {
    
    driving_genes <- names(sort(V[,k], decreasing = TRUE))[1:20]
    
    go_result <- enrichGO(gene = driving_genes,
                          OrgDb = org.Hs.eg.db,
                          keyType = "SYMBOL",
                          ont = "BP", 
                          pAdjustMethod = "bonferroni",
                          pvalueCutoff = 0.05,
                          qvalueCutoff = 0.1)@result
    
    go_result <- go_result %>%
      dplyr::filter(p.adjust < .01)
    
    go_terms <- go_result$Description
    
    genes_vec <- c(genes_vec, paste(driving_genes, collapse = ", "))
    go_terms_vec <- c(go_terms_vec, paste(go_terms, collapse = ", "))
    
  }
  
  go_df <- data.frame(
    driving_genes = genes_vec,
    go_terms = go_terms_vec,
    factor = 1:K
  )
  
  return(go_df)
  
}

gdf_c1 <- get_go_terms(fit$FF)
```

```{r}
knitr::kable(gdf_c1)
```

